name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Caching Library (Temporary Disable to Debug)
      # - uses: actions/cache@v3
      #   with:
      #     path: Library
      #     key: Library-${{ matrix.targetPlatform }}
      #     restore-keys: Library-

      # Free up disk space for Android builds
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: -logFile -

      # Debugging step to check if build directory exists
      - name: Debug Build Path
        run: ls -R build/ || echo "Build folder not found"

      # Upload build artifact (Updated to v4 and ensures it runs even if previous steps fail)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
      - name: Print Unity Editor Log (if build fails)
        if: failure()
        run: |
          echo "Showing Unity Editor Log:"
          cat /github/home/.config/unity3d/Editor.log || echo "No log found"
